# Stage 1: Build
FROM golang:1.22 AS builder
WORKDIR /app

COPY . .


WORKDIR /app/internal/worker
RUN CGO_ENABLED=0 GOOS=linux go build -o worker . 
RUN ls -l 

FROM alpine:latest


COPY --from=builder /app/internal/worker/worker .


RUN chmod +x worker

CMD ["./worker"]
