
FROM golang:1.22 AS builder
WORKDIR /app

COPY . .


WORKDIR /app/internal/master
RUN CGO_ENABLED=0 GOOS=linux go build -o master .  # Build statically
RUN ls -l  # Check if the binary exists

FROM alpine:latest


COPY --from=builder /app/internal/master/master .


RUN chmod +x master

CMD ["./master"]
