apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: dfs-master:v1.0  # Replace with your built image
        ports:
        - containerPort: 50055
---
apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  type: LoadBalancer  # Change to LoadBalancer
  ports:
    - port: 50055
      targetPort: 50055
  selector:
    app: master
